dnf remove -y gnome-connections \
	anaconda \
	gnome-characters \
	gnome-classic-session \
	gnome-contacts \
	gnome-maps \
	gnome-photos \
	gnome-remote-desktop \
	gnome-system-monitor \
	gnome-tour \
	gnome-user-docs \
	yelp \
	cheese \
	rhythmbox \
	totem \
	libreoffice-core \
	gnome-boxes \
	unoconv \
	gnome-weather \
	gnome-clocks \
	gnome-calculator \
	simple-scan \
	mediawriter \
	gnome-font-viewer \
	evince \
	gnome-disk-utility \
	baobab \
	gnome-font-viewer \
	eog \
	gnome-calendar \
	gnome-terminal
